#!/bin/sh

declare -r APP_NAME="${0##*/}"
declare -r VERSION="0.1.8"

print_usage() {
cat << EOF

Usage: $APP_NAME [OPTIONS]

  -V    show program's version number and exit
  -h    show this help message and exit
  -i    increase volume
  -d    decrease volume
  -m    mute volume

EOF
}

while getopts "Vhidm" opt; do
  case $opt in
    i) `dbus-send --type=method_call --dest=com.google.code.Volti /com/google/code/Volti com.google.code.Volti.emit string:'volume-up'`;;
    d) `dbus-send --type=method_call --dest=com.google.code.Volti /com/google/code/Volti com.google.code.Volti.emit string:'volume-down'`;;
    m) `dbus-send --type=method_call --dest=com.google.code.Volti /com/google/code/Volti com.google.code.Volti.emit string:'mute'`;;
    h) print_usage;;
    V) echo "${VERSION}";;
    \?) print_usage;;
  esac
done
