.TH VOLTY 1 "December, 2009"
.SH NAME
Volti \- Tray Audio Volume Control

.SH SYNOPSIS
.B volti
.SH DESCRIPTION
\fBVolti\fP is an GTK+ application for controlling audio volume from system tray/notification area.
.SH DEPENDENCIES
.TP
\fBpygtk\fP 2.16.0 or later
.TP
\fBpyalsaaudio\fP 0.6 or later
.TP
\fBdbus-python\fP (optional, used for keys events via hal and for notifications)
.TP
\fBpython-xlib\fP 0.15rc1 or later (optional, used for keys events)
.SH SEE ALSO
Homepage: http://code.google.com/p/volti/
.SH AUTHOR
Milan Nikolic <gen2brain@gmail.com>
