.TH Volti 1
.SH NAME
\fBVolti\fP \- Tray Audio Volume Control

.SH SYNOPSIS
.B volti
.SH DESCRIPTION
\fBVolti\fP is an GTK+ application for controlling audio volume from system tray/notification area.
.SH DEPENDENCIES
.B Required:
.TP
\fBpygtk\fP 2.16.0 or later
.TP
\fBpyalsaaudio\fP 0.6 or later
.TP
\fBdbus-python\fP 0.80.0 or later

.TP
.B Optional:
.TP
\fBpython-xlib\fP 0.15rc1 or later
.TP
used for keys events as an alternative to hal daemon
.SH BUGS
.TP
Please submit bug reports at:
.TP
\fIhttp://code.google.com/p/volti/issues/entry\fP
.SH SEE ALSO
Homepage: \fIhttp://code.google.com/p/volti/\fP
.SH AUTHOR
Milan Nikolic <\fIgen2brain@gmail.com\fP>
