.TH volti-remote 1
.SH NAME
\fBvolti-remote\fP \- Control Volti from command line

.SH SYNOPSIS
.B volti-remote
.SH DESCRIPTION
\fBvolti-remote\fP sends DBus messages to running Volti instance.
.SH BUGS
.TP
Please submit bug reports at:
.TP
\fIhttp://code.google.com/p/volti/issues/entry\fP
.SH SEE ALSO
Homepage: \fIhttp://code.google.com/p/volti/\fP
.SH AUTHOR
Milan Nikolic <\fIgen2brain@gmail.com\fP>
