.TH volti-mixer 1
.SH NAME
\fBVolti Mixer\fP

.SH SYNOPSIS
.B volti-mixer
.SH DESCRIPTION
\fBVolti Mixer\fP is GTK+ alsa mixer application
.SH DEPENDENCIES
.B Required:
.TP
\fBpygtk\fP 2.16.0 or later
.TP
\fBpyalsaaudio\fP 0.6 or later

.SH BUGS
.TP
Please submit bug reports at:
.TP
\fIhttp://code.google.com/p/volti/issues/entry\fP
.SH SEE ALSO
.BR volti (1), volti-remote (1)
.TP
Homepage: \fIhttp://code.google.com/p/volti/\fP
.SH AUTHOR
Milan Nikolic <\fIgen2brain@gmail.com\fP>
