.TH volti-remote 1
.SH NAME
\fBvolti-remote\fP \- Control Volti from command line

.SH SYNOPSIS
.nf
\fBvolti-remote\fP [\fIOPTION\fP]
.fi
.SH DESCRIPTION
\fBvolti-remote\fP sends DBus messages to running Volti instance.
.SH OPTIONS
.TP
\fB\-h\fR
Display the help message and exit.
.TP
\fB\-i\fR
Increase volume
.TP
\fB\-d\fR
Decrease volume
.TP
\fB\-m\fR
Mute volume
.SH BUGS
.TP
Please submit bug reports at:
.TP
\fIhttp://code.google.com/p/volti/issues/entry\fP
.SH SEE ALSO
.BR volti (1)
.TP
Homepage: \fIhttp://code.google.com/p/volti/\fP
.SH AUTHOR
Milan Nikolic <\fIgen2brain@gmail.com\fP>
